//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RisLab1Server
{
    using System;
    using System.Collections.Generic;
    
    public partial class LocationsByBrandSet
    {
        public int Id { get; set; }
        public int PlantLocationsId { get; set; }
        public int LocationsId { get; set; }
    
        public virtual BrandSet BrandSet { get; set; }
        public virtual LocationsSet LocationsSet { get; set; }
    }
}
