//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RisLab1Server
{
    using System;
    using System.Collections.Generic;
    
    public partial class SmartPhoneSet
    {
        public int Id { get; set; }
        public int BrandId { get; set; }
        public string Model { get; set; }
        public int SpecificationsId { get; set; }
    
        public virtual BrandSet BrandSet { get; set; }
        public virtual SpecificationSet SpecificationSet { get; set; }
    }
}
