//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RisLab1Server
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SmartPhonesModelContainer : DbContext
    {
        public SmartPhonesModelContainer()
            : base("name=SmartPhonesModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Specification> SpecificationSet { get; set; }
        public virtual DbSet<SmartPhone> SmartPhoneSet { get; set; }
        public virtual DbSet<Brand> BrandSet { get; set; }
        public virtual DbSet<LocationsByBrand> LocationsByBrandSet { get; set; }
        public virtual DbSet<Location> LocationSet { get; set; }
    }
}
