//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RisLab1Server
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SmartPhonesEntities : DbContext
    {
        public SmartPhonesEntities()
            : base("name=SmartPhonesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BrandSet> BrandSet { get; set; }
        public virtual DbSet<LocationsByBrandSet> LocationsByBrandSet { get; set; }
        public virtual DbSet<LocationsSet> LocationsSet { get; set; }
        public virtual DbSet<SmartPhoneSet> SmartPhoneSet { get; set; }
        public virtual DbSet<SpecificationSet> SpecificationSet { get; set; }
    }
}
