//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RisLab1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SmartPhoneDbContainer : DbContext
    {
        public SmartPhoneDbContainer()
            : base("name=SmartPhoneDbContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<SmartPhone> SmartPhoneSet { get; set; }
        public virtual DbSet<Specification> SpecificationSet { get; set; }
        public virtual DbSet<Brand> BrandSet { get; set; }
        public virtual DbSet<Locations> LocationsSet { get; set; }
        public virtual DbSet<LocationsByBrand> LocationsByBrandSet { get; set; }
    }
}
