//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RisLab1
{
    using System;
    using System.Collections.Generic;
    
    public partial class SmartPhone
    {
        public int Id { get; set; }
        public int BrandId { get; set; }
        public string Model { get; set; }
        public int SpecificationsId { get; set; }
    
        public virtual Specification Specification { get; set; }
        public virtual Brand Brand { get; set; }
    }
}
